#!/bin/bash

echo "---------------------------------------------"
echo " Starting Lantern configuration..."
echo "---------------------------------------------"

# achieve parallel results as dockerfile
cp -rf /tmp/container/app/* /opt/lantern/
/tmp/container/system/hardware.sh # configure hardware
/tmp/container/system/software.sh # setup all software needed
/tmp/container/system/network.sh # setup discovery and networking
/tmp/container/system/finalize.sh # setup user accounts and service

# mirror docker-entrypoint
/opt/lantern/bin/system-config
chown -R admin /opt/lantern
chgrp -R wheel /opt/lantern
echo "---------------------------------------------"
echo " Your Lantern has been successfully configured"
echo "---------------------------------------------"