#!/bin/bash

echo "---------------------------------------------"
echo " Starting Lantern configuration..."
echo "---------------------------------------------"

# achieve parallel results as dockerfile
cp -rf /tmp/src/app/* /opt/lantern/
/tmp/src/system/hardware.sh # configure hardware
/tmp/src/system/software.sh # setup all software needed
/tmp/src/system/network.sh # setup discovery and networking
/tmp/src/system/service.sh # setup custom services

# prepare our system for first boot
/opt/lantern/bin/init
echo "---------------------------------------------"
echo " Your Lantern has been successfully configured"
echo "---------------------------------------------"