#!/bin/bash

ls -al /tmp/container
# achieve same results as dockerfile + docker-entrypoint
cp -rf /tmp/container/bin/* /usr/local/bin/
cp -rf /tmp/container/ext_node_modules /opt/node_modules
cp -rf /tmp/container/public /opt/public
cp /tmp/container/package.json /opt/
cp /tmp/container/server.js /opt/
mkdir /opt/data

/tmp/container/scripts/hardware # configure hardware
/tmp/container/scripts/network # setup discovery and networking
/tmp/container/scripts/users # setup user accounts
/tmp/container/scripts/db # install pouchdb server and related software
/tmp/container/scripts/service # run lantern app server at boot
/tmp/container/scripts/config # configure our box

ls -al /opt/

echo "---------------------------------------------"
echo " Your Lantern has been successfully configured"
echo "---------------------------------------------"