#!/bin/bash

echo "#############################################"
echo "## Finalize Setup "
echo "#############################################"

touch /etc/systemd/system/lantern.service
cat <<EOF >"/etc/systemd/system/lantern.service"
[Unit]
Description=Lantern Service

[Service]
ExecStart=/opt/lantern/bin/lantern-service
Restart=always

[Install]
WantedBy=multi-user.target
EOF
systemctl enable lantern.service

# create admin user
useradd -m -g wheel -s /usr/bin/zsh admin
echo '%wheel ALL=(ALL) ALL' | EDITOR='tee -a' visudo

# set zsh as the default shell
chsh -s /usr/bin/zsh root && chsh -s /usr/bin/zsh admin
chown admin. /home/admin/.zshrc
echo 'cd /opt/lantern/' >> /home/admin/.zshrc