#!/bin/bash

echo "#############################################"
echo "## Finalize Setup "
echo "#############################################"

# http service
touch /etc/systemd/system/lantern-http.service
cat <<EOF >"/etc/systemd/system/lantern-http.service"
[Unit]
Description=Lantern Database & Web Service

[Service]
ExecStart=/opt/lantern/service/lantern-http
Restart=always

[Install]
WantedBy=multi-user.target
EOF
systemctl enable lantern-http.service


# lora service
touch /etc/systemd/system/lantern-lora.service
cat <<EOF >"/etc/systemd/system/lantern-lora.service"
[Unit]
Description=Lantern LoRa Service

[Service]
ExecStart=/opt/lantern/service/lantern-lora
Restart=always

[Install]
WantedBy=multi-user.target
EOF
systemctl enable lantern-lora.service


# create admin user
useradd -m -g wheel -s /usr/bin/zsh admin
echo '%wheel ALL=(ALL) ALL' | EDITOR='tee -a' visudo

# set zsh as the default shell
chsh -s /usr/bin/zsh root && chsh -s /usr/bin/zsh admin
chown admin. /home/admin/.zshrc
echo 'cd /opt/lantern/' >> /home/admin/.zshrc