#!/bin/bash

echo "#############################################"
echo "## System Setup"
echo "#############################################"

# disable Signature Checks
sed -i -e 's/Required DatabaseOptional/Never/g' /etc/pacman.conf

#install other system requirements
pacman -Syu --noconfirm sudo nano zsh grml-zsh-config \
    bash-completion termite-terminfo \
    nodejs npm python2 base-devel \
    create_ap avahi nss-mdns wpa_supplicant \
    wpa_actiond ifplugd crda dialog
    
ln -s /usr/bin/python2 /bin/python
ln -s /usr/bin/python2-config /bin/python-config
    
# create admin user
useradd -m -g wheel -s /usr/bin/zsh admin
echo '%wheel ALL=(ALL) ALL' | EDITOR='tee -a' visudo

# set zsh as the default shell
chsh -s /usr/bin/zsh root && chsh -s /usr/bin/zsh admin
chown admin. /home/admin/.zshrc
