#!/usr/bin/env python2
import sys
from persistqueue import UniqueQ
inbox = UniqueQ("/opt/lantern/inbox")

def printNow(str):
    print(str)
    sys.stdout.flush()

#-----------------------------------------------------------------------------

to_process = len(inbox)

if to_process > 1:
    printNow("inbox to process:" + str(to_process) + "\n\n")
    
while to_process > 0:
    item = inbox.get()
    printNow(item)
    cmd = "/opt/lantern/bin/process-message " + item
    run = os.system(cmd)
    printNow(run)
