#!/bin/bash

# when we turn service off, automatically resume back to internet usage...
function finish {
    echo "shutting down access point services..."
    exit 0
}

trap finish SIGTERM
trap finish EXIT

echo "make sure we stop any wifi sync..."
systemctl stop sync

echo "bringing wireless access point online..."
/lantern/bin/wifi ap

sleep infinity & wait