#!/bin/bash

# when we turn service off, automatically resume back to internet usage...
function finish {
    echo "shutting down access point services..."
    exit 0
}

trap finish SIGTERM
trap finish EXIT

echo "make sure we stop any pollination..."
systemctl stop pollinate

echo "bringing wireless access point online..."
/lantern/bin/wireless ap

sleep infinity & wait