#!/usr/bin/env python2
import sys
import logging
import os
from persistqueue import UniqueQ
inbox = UniqueQ("/lantern/inbox")

logging.basicConfig(filename="/lantern/logs/inbox.log", level=logging.DEBUG)

def printNow(str):
    print(str)
    logging.info(str)
    sys.stdout.flush()

#-----------------------------------------------------------------------------

to_process = len(inbox)

if to_process > 1:
    printNow("inbox to process:" + str(to_process) + "\n\n")
    
while to_process > 0:
    item = inbox.get()
    printNow(item)
    cmd = "curl -H 'Content-Type: application/json' -X POST --data '{\"message\": \"" + item + "\"}' http://localhost/sync/message"
    printNow(cmd)
    run = os.system(cmd)
    printNow(run)