#!/bin/bash

echo "---------------------------------------------"
echo " Starting Lantern configuration..."
echo "---------------------------------------------"

# achieve parallel results as dockerfile
mv /tmp/lantern/ /opt/lantern/
/tmp/init/hardware.sh # configure hardware
/tmp/init/software.sh # setup all software needed
/tmp/init/network.sh # setup discovery and networking
/tmp/init/service.sh # setup custom services

# prepare our system for first boot
/opt/lantern/bin/init
echo "---------------------------------------------"
echo " Your Lantern has been successfully configured"
echo "---------------------------------------------"