#!/bin/bash

trap "exit" INT

echo "---------------------------------------------"
echo " Starting Lantern configuration..."
echo "---------------------------------------------"

if [[ -f /lantern/system/http ]]; then
	/tmp/init/hardware.sh # configure hardware
	/tmp/init/software.sh # setup all software needed
	/tmp/init/network.sh # setup discovery and networking
	/tmp/init/service.sh # setup custom services
	/lantern/bin/entrypoint # get server modules ready for use
	echo "---------------------------------------------"
	echo " Your Lantern has been successfully configured"
	echo "---------------------------------------------"
else
	ls -al /lantern
	echo "---------------------------------------------"
	echo " WARNING: /lnt not as expected"
	echo "---------------------------------------------"
fi